export const INITIAL_COLLECTIONS = [
  {
    slug: 'after-dark',
    title: 'AFTER DARK',
    subtitle: 'DROP 001 // MIDNIGHT NOCTURNE',
    statement: "THE CITY DOESN'T SLEEP. NEITHER DO WE.",
    description:
      'A study in shadow, deep teal saturation, and heavy architectural silhouettes. Shot across the brutalist transit corridors and industrial docks at 03:00 AM.',
    editorialImage:
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1400&q=85',
    heroImage:
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1600&q=85',
    season: 'SEASON 01',
    year: '2026',
    accentColor: '#042A2B',
    productsCount: 8,
  },
  {
    slug: 'undefined',
    title: 'UNDEFINED',
    subtitle: 'ARCHITECTURAL DRAPES',
    statement: 'FORM WITHOUT PRECEDENT.',
    description:
      'Challenging conventional proportions through extreme dropped shoulder geometry, asymmetric cuts, and tactile washed cottons.',
    editorialImage:
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=1400&q=85',
    heroImage:
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1600&q=85',
    season: 'SEASON 01',
    year: '2026',
    accentColor: '#65743A',
    productsCount: 6,
  },
  {
    slug: 'outsiders',
    title: 'OUTSIDERS',
    subtitle: 'LIMITED CAPSULE',
    statement: 'REJECTING MASS ADOPTION.',
    description:
      'Tactical ballistic Cordura accessories, industrial webbings, and graphic statements created exclusively for those who exist outside the algorithm.',
    editorialImage:
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1400&q=85',
    heroImage:
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1600&q=85',
    season: 'SPECIAL CAPSULE',
    year: '2026',
    accentColor: '#A72608',
    productsCount: 5,
  },
];

export const INITIAL_PRODUCTS = [
  {
    name: 'OBSIDIAN OVERSIZED TEE',
    slug: 'obsidian-oversized-tee',
    description:
      'A heavyweight luxury oversized t-shirt engineered for everyday rebellion. Cut from custom 280 GSM combed cotton with high-density ribbed collar and dropped shoulder geometry.',
    editorialNote: 'Crafted without compromises. The foundation of modern silhouette.',
    price: 1999,
    originalPrice: 2499,
    category: 'tees',
    categoryName: 'OVERSIZED TEES',
    collectionName: 'AFTER DARK',
    collectionSlug: 'after-dark',
    images: [
      'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Obsidian Black', hex: '#191919' },
      { name: 'Washed Ash', hex: '#3a3a3a' },
    ],
    fabricGsm: 280,
    composition: '100% Combed Compact Cotton',
    fit: 'Signature Boxy Oversized Drop Shoulder',
    modelInfo: "Model is 6'1\" / 185cm and wears size Large",
    stock: 24,
    featured: true,
    newArrival: true,
    limitedEdition: true,
    dropNumber: 'DROP 001',
    tags: ['OVERSIZED', 'BLACK', 'TEES', 'ESSENTIAL', 'DROP 001'],
  },
  {
    name: 'SHADOW HEAVYWEIGHT HOODIE',
    slug: 'shadow-heavyweight-hoodie',
    description:
      'Ultra-dense 460 GSM French Terry hoodie built for perpetual urban nocturnes. Features double-layered structured hood with zero drawstrings for pure minimalist brutality.',
    editorialNote: 'Zero branding clutter. Pure weight and structural presence.',
    price: 3499,
    originalPrice: 4299,
    category: 'hoodies',
    categoryName: 'HOODIES',
    collectionName: 'AFTER DARK',
    collectionSlug: 'after-dark',
    images: [
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Pitch Black', hex: '#121212' },
      { name: 'Deep Teal Tint', hex: '#042A2B' },
    ],
    fabricGsm: 460,
    composition: '100% Organic Loopback French Terry',
    fit: 'Sculpted Heavy Oversized Silhouette',
    modelInfo: "Model is 6'2\" / 188cm and wears size XL",
    stock: 15,
    featured: true,
    newArrival: true,
    limitedEdition: false,
    dropNumber: 'DROP 001',
    tags: ['HOODIE', 'HEAVYWEIGHT', 'BLACK', '460GSM', 'BESTSELLER'],
  },
  {
    name: 'TACTICAL WIDE-LEG CARGOS',
    slug: 'tactical-wide-leg-cargos',
    description:
      'Engineered cargo pants tailored with articulated knee darting and gusseted expandable bellows pockets. Finished with adjustable bungee toggle cuffs to style either stacked or flared.',
    editorialNote: 'Industrial utility calibrated for civilian street dominance.',
    price: 3199,
    originalPrice: 3899,
    category: 'cargos',
    categoryName: 'CARGOS',
    collectionName: 'AFTER DARK',
    collectionSlug: 'after-dark',
    images: [
      'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Stealth Black', hex: '#151515' },
      { name: 'Military Olive', hex: '#2C3529' },
    ],
    fabricGsm: 320,
    composition: '100% Cotton Ripstop Twill with Water-Repellent Treatment',
    fit: 'Wide-Leg Relaxed with Articulated Knees',
    modelInfo: "Model is 6'0\" / 183cm and wears size M (32 inch waist)",
    stock: 18,
    featured: true,
    newArrival: false,
    limitedEdition: false,
    dropNumber: 'DROP 001',
    tags: ['CARGOS', 'TACTICAL', 'RIPSTOP', 'PANTS', 'BOTTOMS'],
  },
  {
    name: 'BRUTALIST GRAPHIC CREWNECK',
    slug: 'brutalist-graphic-crewneck',
    description:
      'High-density screenprint on pre-shrunk 380 GSM fleece. Back panel features abstract typography reflecting architectural blueprints of Mumbai modernism.',
    editorialNote: 'Art meets garment architecture.',
    price: 2799,
    originalPrice: 3299,
    category: 'sweatshirts',
    categoryName: 'SWEATSHIRTS',
    collectionName: 'UNDEFINED',
    collectionSlug: 'undefined',
    images: [
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Washed Concrete', hex: '#4A4A4A' },
      { name: 'Rust Orange', hex: '#A72608' },
    ],
    fabricGsm: 380,
    composition: '90% Cotton, 10% Poly Fleece',
    fit: 'Drop Shoulder Boxy Fit',
    modelInfo: "Model is 5'11\" / 180cm and wears size L",
    stock: 9,
    featured: false,
    newArrival: true,
    limitedEdition: true,
    dropNumber: 'DROP 002',
    tags: ['CREWNECK', 'GRAPHIC', 'FLEECE', 'DROP 002'],
  },
  {
    name: 'NOCTURNE NYLON BOMBER JACKET',
    slug: 'nocturne-nylon-bomber-jacket',
    description:
      'Water-resistant matte crinkled nylon shell filled with lightweight thermal insulation. Finished with two-way heavy industrial matte black metal zippers.',
    editorialNote: 'Designed for midnight shifts and winter storms.',
    price: 4999,
    originalPrice: 5999,
    category: 'outerwear',
    categoryName: 'OUTERWEAR',
    collectionName: 'AFTER DARK',
    collectionSlug: 'after-dark',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Midnight Onyx', hex: '#0B0C10' },
      { name: 'Cyber Smoke', hex: '#2A3439' },
    ],
    fabricGsm: 210,
    composition: '100% Recycled Crinkle Nylon Shell, Thinsulate Padding',
    fit: 'Cropped Body with Elongated Arms',
    modelInfo: "Model is 6'1\" / 185cm and wears size L",
    stock: 7,
    featured: true,
    newArrival: true,
    limitedEdition: true,
    dropNumber: 'DROP 001',
    tags: ['JACKET', 'OUTERWEAR', 'NYLON', 'LIMITED'],
  },
  {
    name: 'REBELLION ACID-WASH OVERSIZED TEE',
    slug: 'rebellion-acid-wash-oversized-tee',
    description:
      'Individually enzyme-washed and hand-distressed so no two pieces are identical. Features raw hems and distressed micro-abrasions along collar cuffs.',
    editorialNote: 'One-of-one character straight out of the dye vat.',
    price: 2199,
    originalPrice: 2699,
    category: 'tees',
    categoryName: 'OVERSIZED TEES',
    collectionName: 'UNDEFINED',
    collectionSlug: 'undefined',
    images: [
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Mineral Washed Black', hex: '#292826' },
      { name: 'Bleached Sage', hex: '#586957' },
    ],
    fabricGsm: 260,
    composition: '100% Premium Cotton with Enzyme Wash',
    fit: 'Loose Drape Relaxed Boxy',
    modelInfo: "Model is 5'10\" / 178cm and wears size M",
    stock: 22,
    featured: false,
    newArrival: false,
    limitedEdition: false,
    dropNumber: 'DROP 001',
    tags: ['TEES', 'WASHED', 'DISTRESSED', 'STREET'],
  },
  {
    name: 'OUTSIDERS TACTICAL CROSSBODY BAG',
    slug: 'outsiders-tactical-crossbody-bag',
    description:
      'Ballistic Cordura 1000D body with Fidlock magnetic buckle closure. Waterproof seam-taped zippers and quick-release nylon webbing strap.',
    editorialNote: 'Keep your essentials secured in high-speed transit.',
    price: 1899,
    originalPrice: 2299,
    category: 'accessories',
    categoryName: 'ACCESSORIES',
    collectionName: 'OUTSIDERS',
    collectionSlug: 'outsiders',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['M'],
    colors: [{ name: 'Matte Tactical Black', hex: '#111111' }],
    fabricGsm: 350,
    composition: '1000D Ballistic Cordura Nylon + Mil-spec hardware',
    fit: 'Adjustable Modular Crossbody',
    modelInfo: 'One Size fits all, adjustable from 70cm to 140cm strap length',
    stock: 30,
    featured: true,
    newArrival: true,
    limitedEdition: false,
    dropNumber: 'DROP 001',
    tags: ['BAG', 'ACCESSORIES', 'CORDURA', 'TACTICAL'],
  },
  {
    name: 'INNER CIRCLE HEAVY KNIT BEANIE',
    slug: 'inner-circle-heavy-knit-beanie',
    description:
      'Ribbed fishermen beanie knit from 100% Australian Merino Wool blend. Finished with tonal matte rubberized logo badge.',
    editorialNote: 'Low-profile crown. Heavy thermal retention.',
    price: 999,
    originalPrice: 1299,
    category: 'accessories',
    categoryName: 'ACCESSORIES',
    collectionName: 'AFTER DARK',
    collectionSlug: 'after-dark',
    images: [
      'https://images.unsplash.com/photo-1576871337622-98d48d1cf531?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=1200&q=85',
    ],
    sizes: ['S', 'M'],
    colors: [
      { name: 'Jet Black', hex: '#000000' },
      { name: 'Slate Moss', hex: '#3B443B' },
    ],
    fabricGsm: 180,
    composition: '50% Merino Wool, 50% Anti-Pilling Acrylic',
    fit: 'Fitted Shallow Crown Fishermen Cut',
    modelInfo: 'One Size Stretch Fit',
    stock: 45,
    featured: false,
    newArrival: false,
    limitedEdition: false,
    dropNumber: 'DROP 001',
    tags: ['BEANIE', 'WOOL', 'ACCESSORIES', 'WINTER'],
  },
];
